# admin/states.py
"""Состояния диалогов админки — централизованное управление"""
from telegram.ext import ConversationHandler

# Диалог добавления темы (5 шагов)
WAITING_LINK = 0
WAITING_HASHTAG = 1
WAITING_START_DATETIME = 2
WAITING_END_DATETIME = 3
WAITING_POINT_VALUE = 4
EDIT_TOPIC_TIMEOUT = 20

# Диалог редактирования темы
EDIT_TOPIC_SELECT = 5
EDIT_TOPIC_FIELD = 6
EDIT_TOPIC_VALUE = 7

# Диалог удаления темы
DELETE_TOPIC_SELECT = 8
DELETE_CONFIRM = 9

# Конвертация в ConversationHandler.states
ADD_TOPIC_STATES = {
    WAITING_LINK: WAITING_LINK,
    WAITING_HASHTAG: WAITING_HASHTAG,
    WAITING_START_DATETIME: WAITING_START_DATETIME,
    WAITING_END_DATETIME: WAITING_END_DATETIME,
    WAITING_POINT_VALUE: WAITING_POINT_VALUE
}

EDIT_TOPIC_STATES = {
    EDIT_TOPIC_SELECT: EDIT_TOPIC_SELECT,
    EDIT_TOPIC_FIELD: EDIT_TOPIC_FIELD,
    EDIT_TOPIC_VALUE: EDIT_TOPIC_VALUE,
    EDIT_TOPIC_TIMEOUT: EDIT_TOPIC_TIMEOUT
}

DELETE_TOPIC_STATES = {
    DELETE_TOPIC_SELECT: DELETE_TOPIC_SELECT,
    DELETE_CONFIRM: DELETE_CONFIRM
}